name: PIXLEnv
channels:
  - conda-forge
  - defaults
dependencies:
  - boto3=1.18.21
  - importlib-metadata=6.0.0
  - importlib_resources=6.1.0
  - ipykernel=6.25.0
  - ipython=8.15.0
  - ipywidgets=8.0.4
  - jupyter=1.0.0
  - jupyterlab=3.2.1
  - matplotlib=3.7.2
  - notebook=6.5.4
  - numba=0.58.0
  - numpy=1.24.3
  - onnx=1.10.1
  - pandas=1.3.4
  - pip=23.3
  - protobuf=3.16.0
  - pygments=2.15.1
  - pyro-api=0.1.2
  - pyro-ppl=1.8.6
  - python=3.9.18
  - pytorch=1.12.1
  - scikit-image=0.19.3
  - scikit-learn=1.0.1
  - scipy=1.10.1
  - seaborn=0.11.2
  - setuptools=68.0.0
  - toolz=0.11.2
  - tqdm=4.65.0
  - typing-extensions=4.7.1
  - umap-learn=0.5.2
  - pip:
      - torcheval==0.0.7
